{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "lugh.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  selector:
    app: lugh-redis
  ports:
    - port: {{ .Values.redis.port }}
      targetPort: {{ .Values.redis.port }}
      name: redis
{{- end }}
