# Generated by Django 5.2.12 on 2026-05-25 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PLCDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('ams_net_id', models.CharField(help_text='TwinCAT AMS Net ID, e.g. 192.168.0.158.1.1', max_length=23)),
                ('ads_port', models.PositiveIntegerField(default=851, help_text='TwinCAT 3 runtime port (default 851)')),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text="Whether this is the user's primary device")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plc_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PLC Device',
                'verbose_name_plural': 'PLC Devices',
                'ordering': ['-updated_at'],
                'unique_together': {('owner', 'name')},
            },
        ),
        migrations.CreateModel(
            name='DiscoveryCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbols_json', models.JSONField(default=list)),
                ('scanned_at', models.DateTimeField(auto_now=True)),
                ('scan_duration_ms', models.PositiveIntegerField(default=0)),
                ('symbol_count', models.PositiveIntegerField(default=0)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discovery_cache', to='find_device.plcdevice')),
            ],
            options={
                'verbose_name': 'Discovery Cache',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('dark', 'Dark'), ('light', 'Light')], default='dark', max_length=10)),
                ('push_notifications_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
            },
        ),
    ]
