# Generated by Django 5.2.12 on 2026-06-29 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_device', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('building', models.CharField(blank=True, max_length=100)),
                ('floor', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='plcdevice',
            name='is_default',
            field=models.BooleanField(default=False, help_text="Legacy: whether this was the registering user's primary device"),
        ),
        migrations.AddField(
            model_name='plcdevice',
            name='apartment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plc_device', to='find_device.apartment'),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='find_device.apartment')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'unique_together': {('apartment', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ApartmentMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('resident', 'Resident'), ('installer', 'Installer')], default='resident', max_length=12)),
                ('is_default', models.BooleanField(default=False, help_text="Which apartment this user's app opens to when they have more than one")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='find_device.apartment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartment_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', 'apartment__name'],
                'unique_together': {('user', 'apartment')},
            },
        ),
        migrations.CreateModel(
            name='ApartmentDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('dali', 'DALI dimmer'), ('relay', 'Wall relay'), ('switch', 'Switch input'), ('curtain', 'Curtain motor'), ('appliance', 'Appliance relay'), ('door_sensor', 'Door sensor'), ('window_sensor', 'Window sensor'), ('motion_sensor', 'Motion sensor')], max_length=20)),
                ('channel_or_index', models.PositiveIntegerField(blank=True, null=True)),
                ('gvl_name', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='find_device.apartment')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='find_device.room')),
            ],
            options={
                'ordering': ['device_type', 'sort_order', 'channel_or_index'],
                'indexes': [models.Index(fields=['apartment', 'device_type'], name='find_device_apartme_907f02_idx')],
            },
        ),
    ]
