# Generated by Django 5.2.12 on 2026-07-08 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_device', '0006_map_editor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canvasobject',
            name='color',
            field=models.CharField(blank=True, help_text='Hex e.g. #FF5A3E', max_length=20),
        ),
        migrations.AlterField(
            model_name='mapversion',
            name='snapshot',
            field=models.JSONField(help_text='Full serialized list of CanvasObject dicts'),
        ),
    ]
