# Generated by Django 5.2.12 on 2026-07-20 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_device', '0007_alter_canvasobject_color_alter_mapversion_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canvasobject',
            name='layer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canvas_objects', to='find_device.maplayer'),
        ),
        migrations.AlterField(
            model_name='canvasobject',
            name='layout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canvas_objects', to='find_device.maplayout'),
        ),
    ]
