# Generated by Django 5.2.12 on 2026-07-31 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_device', '0008_related_name_canvas_objects'),
    ]

    operations = [
        migrations.AddField(
            model_name='plcdevice',
            name='down_since',
            field=models.DateTimeField(blank=True, help_text="Set when check_plc_heartbeat first observes this device unreachable (ADS and Modbus both down); cleared on recovery. Persisted (not in-memory) so a Celery worker restart mid-outage doesn't lose track of it or re-fire the outage-start alert.", null=True),
        ),
    ]
