# Generated by Django 5.2.12 on 2026-08-24 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_device', '0018_alter_discoveredcapability_test_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceAddressScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Short, versioned identifier, e.g. 'apt16_dali_v1'. A different PLC generation or naming convention is a new row with a new name, never an edit to an existing one that's already in use — devices already pointing at a scheme must not have its meaning change under them.", max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('gvl', models.CharField(help_text='e.g. gvlController', max_length=50)),
                ('read_var_template', models.CharField(blank=True, max_length=150)),
                ('write_var_template', models.CharField(blank=True, max_length=150)),
                ('commit_var_template', models.CharField(blank=True, help_text="Optional rising-edge 'commit' variable for the write-then-pulse pattern DaliChannel/WallRelay already use (see devices.py) — leave blank if this scheme's write_var_template alone is sufficient.", max_length=150)),
                ('index_offset', models.IntegerField(default=0, help_text="Added to the owning device's channel_or_index before it's substituted into a template as {index}.")),
                ('plc_type', models.CharField(choices=[('BOOL', 'BOOL'), ('BYTE', 'BYTE'), ('INT', 'INT'), ('UINT', 'UINT'), ('DINT', 'DINT'), ('UDINT', 'UDINT'), ('SINT', 'SINT'), ('USINT', 'USINT'), ('WORD', 'WORD'), ('DWORD', 'DWORD'), ('REAL', 'REAL'), ('LREAL', 'LREAL'), ('STRING', 'STRING'), ('WSTRING', 'WSTRING')], default='BOOL', max_length=10)),
                ('protocol', models.CharField(choices=[('ads', 'ADS only'), ('modbus', 'Modbus only'), ('both', 'ADS with Modbus fallback')], default='ads', max_length=10)),
                ('widget_type', models.CharField(blank=True, help_text="One of find_device.discovery.classifier's WIDGET_* values, e.g. 'dali_slider', 'toggle'. Blank is fine — the UI falls back to device_type-based rendering.", max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Device Address Scheme',
                'verbose_name_plural': 'Device Address Schemes',
            },
        ),
        migrations.AddField(
            model_name='apartmentdevice',
            name='address_scheme',
            field=models.ForeignKey(blank=True, help_text="Optional. Leave blank to use the built-in Python class for this device_type (the normal, tested path). Set this only for a device whose GVL layout doesn't match any existing hardcoded class — see docs/plc-integration.md.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='find_device.deviceaddressscheme'),
        ),
    ]
