# Generated by Django 5.2.12 on 2026-08-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_device', '0019_deviceaddressscheme_apartmentdevice_address_scheme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentdevice',
            name='device_type',
            field=models.CharField(choices=[('dali', 'DALI dimmer'), ('relay', 'Wall relay'), ('switch', 'Switch input'), ('curtain', 'Curtain motor'), ('appliance', 'Appliance relay'), ('door_sensor', 'Door sensor'), ('window_sensor', 'Window sensor'), ('motion_sensor', 'Motion sensor'), ('toggle', 'Named relay/light'), ('named_switch', 'Named switch input'), ('custom', 'Custom (scheme-driven)')], max_length=20),
        ),
    ]
