# Generated by Django 5.2.12 on 2026-09-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_device', '0020_alter_apartmentdevice_device_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='auto_sunset_sunrise',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='christmas_mode_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apartment',
            name='poll_interval_s',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='apartment',
            name='sunrise_override_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='sunset_override_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
